### PR TITLE
Fix problems when converting Date object to string

### LINKED ISSUE #5: Problems when transforming Date object to string
Hi Thomas,
Thank you very much for creating this awesome lib!

I think I found two problems in the code that transforms a Date object into a string. I filed just one issue for both, because they are caused by the same couple lines of code. If they make sense, please let me know if you want me to create a pull request for that. Thanks :)

**1. Passing a Date object belonging to October, November or December fails validation.**
When building a date string from a Date object:

```
var pad = function(d) {
    return d < 10 ? '0' + d : d;
};

...

params.start = typeof params.start === 'object' ?
    (params.start.getFullYear() + (pad(params.start.getMonth() + 1)) +
        pad(params.start.getDate())) :
    params.start;
```

`getFullYear`, `getMonth` and `getDate` return numeric values. And `pad` only returns a string when actually padding. If the month is October, November or December, `pad` will return the value as is (numeric), and the concatenation will become a numerical sum, resulting in a validation error in the next regular expression check.

**2. Passing a Date object with time zone information may result in shifted dates.**
If the machine executing pageview.js has a timezone like GMT-5 and it tries to execute:

```
var pageviews = require('pageviews');

pageviews.getAggregatedPageviews({
    project: 'all-projects',
    granularity: 'daily',
    start: new Date('2016-01-01'),
    end: new Date('2016-01-31')
});
```

`new Date('2016-01-01')` will create a Date object with the following value `Thu Dec 31 2015 19:00:00 GMT-0500 (EST)`. And the code that generates a date string uses `getFullYear`, `getMonth` and `getDate`, which in this particular case will return `2015`, `12` and `31` respectively, generating a date string like `2015-12-31` instead of `2016-01-01`. This would happen with the end date as well.

Cheers!

### PR DESCRIPTION
**Pull request by marcelrf**
This patch tries to fix https://github.com/tomayac/pageviews.js/issues/5 by making sure `pad` always returns a string, so that date strings are correctly concatenated; and by replacing the calls to `getFullYear`, `getMonth`, `getDate` and `getHours` to their UTC counterparts.

### CODE REVIEW

**Comment by tomayac** [comment]
Brilliant, thanks a ton! Could I ask you to bump the version numbers in package.json and bower.json to 1.0.8 and to execute `npm run build` to create an up-to-date pageviews.min.js, please? I will merge right away then. ¡Gracias!

**Comment by tomayac** [comment]
O més ben dit: gràcies :-)

**Comment by marcelrf** [comment]
Sure! I bumped the versions in the config files. Sorry I forgot that. The pageviews.min.js file was already up-to-date I think. I amended this changes to the same commit.

I see you like languages :]
Danke vielmals!

**Comment by tomayac** [comment]
Perfect, thanks a ton :-) Greatly appreciated!

**Pull request merged**
